name: Docker build and push

on:
  push:
    branches: [ "main" ]
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo & Build
      uses: actions/checkout@v2
    - run: docker buildx build -t image-name:0.1 ./docker-images/
  
    
    - name: Build & Push 
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: image-name:0.1
        file: ./docker-images/
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
