name: Docker build and push

on:
  push:
    branches: [ "main" ]
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name : Checkout repo
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        docker build -t --tag image-name:$(date +%s) ./docker-images/
