name: Docker build and push

on:
  push:
    branches: [ "main" ]
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo & Build
      uses: actions/checkout@v2
    
    - name: Build & Push 
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: josh-image
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
