name: Docker build and push

on:
  push:
    branches: [ "main" ]
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo & Build
      uses: actions/checkout@v2
    
    - name: Build & Push 
      uses: mr-smithers-excellent/docker-build-push@v6
      run: docker buildx build -t image-name:$(date +%s) ./docker-images/
      with:
        image: image-name
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
