##TODO: 

##- Ejecutarse cuando se cree una release no una rama

##- Separar el step de build y el de push en jobs ((((outputs))))

##- No puedo usar build and push de market

##


name: Create and publish a Docker image

on:
  push:
    branches:
      - main
    tags:
      - 0.0.1

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions: write-all
#      contents: read-all
#      packages: write-all
 #     id-token: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


      - name: Build Docker image
        id: build-image
        env:
          DOCKER_REGISTRY: ${{ steps.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
          BUILDX_CONFIG: ~/.docker/buildx
        run: |
          cd docker-images
          ls -la
          docker build -t test-image .
#        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
#        with:
#          context: ./docker-images/
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}


      - name: Push Docker image
        id: push-image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker push test-image
#        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
#        with:
#          context: ./docker-images/
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
